school/classroom/urls.py
from django.urls import path
from .views import (HomeView,ThankYouView, 
                    ContactFormView,TeacherCreateView,
                    TeacherListView, TeacherDetailView,
                    UpdateTeacherView,DeleteTeacherView)

app_name = 'classroom'

urlpatterns = [
    path('',HomeView.as_view(),name='home'),
    path('thank_you/',ThankYouView.as_view(),name='thank_you'),
    path('contact/',ContactFormView.as_view(),name='contact'),
    path('create_teacher/',TeacherCreateView.as_view(),name='create_teacher'),
    path('list_teacher/',TeacherListView.as_view(),name='list_teacher'),
    path('teacher_detail/<int:pk>',TeacherDetailView.as_view(),name='teacher_detail'),
    path('update_teacher/<int:pk>',UpdateTeacherView.as_view(),name='update_teacher'),
    path('delete_teacher/<int:pk>',DeleteTeacherView.as_view(),name='delete_teacher'),

]

school/school/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("classroom/", include('classroom.urls') )
]

school/classroom/models.py
from django.db import models

# Create your models here.

class Teacher(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    subject = models.CharField(max_length=30)

    def __str__(self):
        return f"{self.first_name} {self.first_name} teaches {self.subject}." 

school/classroom/forms.py
from django import forms

class ContactForm(forms.Form):
    name = forms.CharField()
    message = forms.CharField(widget=forms.Textarea)

school/classroom/views.py
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.views.generic import TemplateView, FormView, CreateView, ListView, DetailView, UpdateView, DeleteView
from classroom.forms import ContactForm
from classroom.models import Teacher
# Create your views here.

class HomeView(TemplateView):
    template_name = 'classroom/home.html'

class ThankYouView(TemplateView):
    template_name = 'classroom/thank_you.html'

class ContactFormView(FormView):
    form_class = ContactForm
    template_name = 'classroom/contact.html'

    # success URL ?
    # actual URL at the top of the browser.
    success_url = reverse_lazy("classroom:thank_you")

    # what to do with form? 
    def form_valid(self,form):
        print(form.cleaned_data)
        return super().form_valid(form)


class TeacherCreateView(CreateView):
    model = Teacher
    fields = "__all__"

    success_url = reverse_lazy("classroom:thank_you")

class TeacherListView(ListView):
    model = Teacher
    context_object_name = "teacher_list"


class TeacherDetailView(DetailView):
    model = Teacher

    # PK ---> {{teacher}}

class UpdateTeacherView(UpdateView):
    model = Teacher
    fields = "__all__"

    success_url = reverse_lazy("classroom:list_teacher")


class DeleteTeacherView(DeleteView):
    model = Teacher
    success_url = reverse_lazy("classroom:list_teacher")

school/classroom/templates/classroom/contact.html
<h1>Form View Template (contact.html)</h1>

<form method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Submit">
</form>

school/classroom/templates/classroom/home.html
<h1>Welcome to home.html</h1>


<ul>
<li>
    <a href="{% url "classroom:thank_you" %}">Thank you Page Link</a>
</li>
<li>
    <a href="{% url "classroom:contact" %} ">Contact Form Page</a>
</li>
<li>
    <a href="{% url "classroom:create_teacher" %} ">Create Teacher Page</a>
</li>
<li>
    <a href="{% url "classroom:list_teacher" %} ">List Teacher Page</a>
</li>
</ul>

school/classroom/templates/classroom/teacher_confirm_delete.html
<form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete {{teacher.first_name}}</p>
    {{form}}
    <input type="submit" value="Confirm">

</form>

school/classroom/templates/classroom/teacher_detail.html
<h1>Detail View of Techer</h1>
{{teacher}}

school/classroom/templates/classroom/teacher_form.html
<h1>Techer Form</h1>
<form method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Submit">
</form>

school/classroom/templates/classroom/teacher_list.html
<h1>List of Teachers (ListView)</h1>
<ul>
    {% for teacher in teacher_list %}
        
            <li>
                <a href="/classroom/teacher_detail/{{teacher.id}}">{{teacher.first_name}} {{teacher.last_name}}</a>
                <a href="/classroom/update_teacher/{{teacher.id}}">Edit..</a>
                {% comment %} <form action="/classroom/update_teacher/{{teacher.id}}">
                    <input type="submit" value="Edit" />
                </form>                 {% endcomment %}
                <a href="/classroom/delete_teacher/{{teacher.id}}">Delete..</a>
            </li>
        
    {% endfor %}

</ul>
<p><a href="{% url "classroom:home" %}">Home Page</a></p>

school/classroom/templates/classroom/thank_you.html
<h1>Thank you~~</h1>
<p><a href="{% url "classroom:home" %}">Home Page</a></p>